openapi: "3.0.0"
info:
  title: AddressAPI
  version: 1.0.0
paths:
  /getAddressByNIC/:
    get:
      summary: Get the address of the user with nic
      description: Get the address records from the AddressAPI database of the user
      parameters:
        - in: query
          name: nic
          description: nic of the user in the record
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nic:
                    type: integer
                  address:
                    type: string

        "404":
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  description:
                    type: string

        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

      deprecated: false
      security: []
